### ISSUE TITLE
review of new base class design

### ISSUE THREAD

**Issue by fkiraly** [NorskRegnesentral/skchange#12]
My thoughts about the new base class design.

Overall, I am quite impressed. This seems to be a working prototype that proves that transformations can be used as the base class.
I also see there is a combination of very pragmatic corner cutting (which could be leveraged for future redesign). I suppose this as you need sth to work quickly, and it is great to see it works.

I also have some questions and worries.

* You are overriding `predict` in the base class, so I wonder why the tests are not breaking here. The `BaseTransformer` contract seems not to be satisfied, e.g., broadcasting will not work.
* is this upwards compatibility safe with changes to `sktime` `BaseTransformer`? Noting that this is more than just an API extension, it is relying on certain private interfaces of the boilerplate that may change.
* what are your thoughts on being able to use the components in pipelines? Do you have good test cases for this?

**Comment by Tveten** [comment]
Just for reference. Based on your worry about depending on BaseTransformer, the dependency is now on BaseEstimator instead. See issues:

- https://github.com/NorskRegnesentral/skchange/pull/14
- https://github.com/sktime/sktime/pull/7067

**Comment by Tveten** [comment]
I'm glad you like it. On that note: Lots of credits to https://github.com/sktime/sktime/issues/3214.

**Comment by Tveten** [comment]
Regarding test cases for pipelines, the most useful case I can think of for now is to do standardisation -> detection. Maybe someone also wants to do detection -> remove anomalies.

**Comment by fkiraly** [comment]
standardisation -> detection:
https://github.com/sktime/sktime/pull/7071
as special case of a pipeline transformer - detector

detection -> remove anomalies
https://github.com/sktime/sktime/pull/7072
as special case of a composite transformer (coerced detector) - transformer

**Comment by Tveten** [comment]
Fixed here: https://github.com/NorskRegnesentral/skchange/pull/49
