### ISSUE TITLE
Make a detector naming convention and update detector names

### ISSUE THREAD

**Issue by Tveten** [NorskRegnesentral/skchange#30]
TODO:

- Capital letters for abbreviations: PELT rather than Pelt. CAPA rather than Capa.
- Moscore -> MovingScore.

**Comment by fkiraly** [comment]
Once you have decided on "final" names, could you kindly notify @shivamJ07 in https://github.com/sktime/sktime/issues/7351, so we use those for aliasing inside `sktime`?
