### ISSUE TITLE
[DOC] in docstrings, should we replace single backtick by double backtick?

### ISSUE THREAD

**Issue by fkiraly** [NorskRegnesentral/skchange#43]
In rst compiled documentation from docstrings, single backticks will not display as code block.
Should we replace by double backtick?

Or is this fine for the `skchange` docs?

**Comment by Tveten** [comment]
I've followed the [Numpy style guide](https://numpydoc.readthedocs.io/en/latest/format.html#sections), which recommends single backticks. So I think that's fine for `skchange` for now. Do you have an example where this doesn't work well?

**Comment by Tveten** [comment]
I might not have read the style guide well enough. I see there's a distinction of using single backticks for attributes, methods, classes, functions and parameters, and double backticks otherwise. 

Is it the "otherwise" part, like code blocks, you think should be updated?
